logging:
    level:
        org.springframework.web: INFO
        com.github.binarywang.demo.wx.cp: DEBUG
        me.chanjar.weixin: DEBUG
    file:
        path: ./
wechat:
    cp:
        corpId: "ww0db1bc3ecc363cfc"
        appConfigs:
            -   agentId: 1000002
                secret: "oCVhYswuy8D9dcsKsWFswA7M913oVezqp72y4uJ9R-I"
                token: "3hVOIUc7TAlPZ6pk46pblwbj3hl5Uz"
                aesKey: "MsqxNquQnFpaJ3bLoB43hRYhgYE6PkWnMfeUIjIcLjg"
server:
    port: 8021
sentry:
    dsn: https://71c3f890943246b7be31d0805e849998@o318524.ingest.sentry.io/5497256
spring:
    jpa:
        hibernate:
            ddl-auto: update
    datasource:
        url: "jdbc:mysql://182.92.227.90:3306/wechat?characterEncoding=utf8"
        username: "lzzj"
        password: "Gyzsq89897188.a"
